In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.cross_validation import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn import svm

from sklearn.metrics import confusion_matrix, classification_report,accuracy_score



from datetime import datetime
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler 
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN


C:\Anaconda\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [97]:
data = pd.read_csv('video_products_100000_sample.csv',
                   encoding='utf-8',  
                    engine='python',
                   memory_map=True,
                   error_bad_lines=False,
                    na_values='NaN')

In [98]:
data=data.dropna()

In [59]:
data=data.sample(1000)

In [80]:
data['pos_neg']=['1' if x> 3 else '0' for x in data.star_rating]

In [ ]:
data=data[['review_body','review_headline','star_rating','pos_neg']]

In [ ]:
data.to_csv('rewrite_video_game_.csv', encoding='utf-8')

In [99]:
X=data['review_body'].values

In [100]:
y=data['star_rating']

In [84]:
X=data['review_headline'].values

In [85]:
y=data['pos_neg']

In [101]:
X.shape, y.shape

((100000,), (100000,))

In [104]:
#TfidfVectorizer
vect=TfidfVectorizer()
X = vect.fit_transform(X)
print(X.shape)

C:\Anaconda\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


(100000, 141359)


In [ ]:
from imblearn.under_sampling import AllKNN 
print('Original dataset shape {}'.format(Counter(y)))

allknn = AllKNN(random_state=42)
X_res, y_res = allknn.fit_sample(X, y)
print('Resampled dataset shape {}'.format(Counter(y_res)))


In [105]:
#Obtaining predictions by cross-validation
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

predicted=cross_val_predict(nbclf,X,y,cv=10)
print(classification_report(y,predicted))
print(confusion_matrix(y,predicted))



             precision    recall  f1-score   support

          1       0.00      0.00      0.00      7116
          2       0.00      0.00      0.00      4880
          3       0.20      0.00      0.00      9175
          4       0.21      0.00      0.00     19111
          5       0.60      1.00      0.75     59718

avg / total       0.42      0.60      0.45    100000

[[    0     0     0     1  7115]
 [    0     0     0     1  4879]
 [    0     0     1     7  9167]
 [    1     0     0    16 19094]
 [    5     4     4    51 59654]]


In [106]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=100)

In [113]:
# Perform SMOTE
t1 = datetime.now()
print('Original dataset shape {}'.format(Counter(y_train)))
sm = SMOTE(random_state=100)
X_res, y_res = sm.fit_sample(X_train, y_train) 
print('Resampled dataset shape {}'.format(Counter(y_res)))
print(datetime.now() - t1)

Original dataset shape Counter({5: 41824, 4: 13372, 3: 6452, 1: 4959, 2: 3393})
Resampled dataset shape Counter({5: 41824, 2: 41824, 1: 41824, 4: 41824, 3: 41824})
0:01:31.276975


In [116]:
# use Naive Bayes to predict the star rating
nb = MultinomialNB(alpha=1)
nb.fit(X_res, y_res)
y_pred_class = nb.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y,predicted))




             precision    recall  f1-score   support

          1       0.60      0.15      0.24      2157
          2       0.13      0.55      0.21      1487
          3       0.21      0.24      0.22      2723
          4       0.31      0.37      0.34      5739
          5       0.82      0.62      0.71     17894

avg / total       0.62      0.50      0.53     30000

[[    0     0     0     1  7115]
 [    0     0     0     1  4879]
 [    0     0     1     7  9167]
 [    1     0     0    16 19094]
 [    5     4     4    51 59654]]


# AAAAAAAAAAAAAAAAAAAAAA

In [52]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import cross_val_predict

from sklearn import cross_validation
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
nbclf=MultinomialNB(alpha=1)

# BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

In [ ]:
import numpy as np
from sklearn import metrics

fpr, tpr, thresholds = metrics.roc_curve(y, predicted, pos_label=2)
metrics.auc(fpr, tpr)


In [95]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

clf = svm.SVC(kernel='linear', C=1)
nbclf=MultinomialNB(alpha=1)

cv = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
score=cross_val_score(nbclf, X, y, cv=cv)
score
                           

array([0.82, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82])

In [ ]:
from sklearn.cross_validation import cross_val_predict

from sklearn import cross_validation
from sklearn.model_selection import cross_val_score

In [ ]:
nbclf=MultinomialNB(alpha=1)
svmclf=svm.SVC(C=1.0,kernel='linear')
from sklearn.pipeline import Pipeline
text_clf=Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB()),])
score = cross_validation.cross_val_predict(text_clf,X,y,cv=10)
print(classification_report(y,score))

In [ ]:
train_dtm

In [ ]:
# SMOTE
t1 = datetime.now()
print('Original dataset shape {}'.format(Counter(y)))
sm = SMOTE(random_state=100)
X_res, y_res = sm.fit_sample(train_dtm, y) 
print('Resampled dataset shape {}'.format(Counter(y_res)))
print(datetime.now() - t1)

In [ ]:
X_test

In [ ]:
X_train

In [ ]:

from sklearn.metrics import confusion_matrix, classification_report
t1 = datetime.now()
#LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred_class = logreg.predict(X_test)

print(classification_report(y_test,y_pred_class))
print(datetime.now() - t1)

In [ ]:
# Logistic Regression CV
from sklearn.linear_model import LogisticRegressionCV
t1 = datetime.now()

logreg = LogisticRegressionCV(cv=10)
logreg.fit(X_train, y_train)
y_pred_class = logreg.predict(X_test)

print(classification_report(y_test,y_pred_class))
print(datetime.now() - t1)

In [ ]:
#LinearSVC
from sklearn.svm import LinearSVC
t1 = datetime.now()

#LinearSVC
lin_clf = LinearSVC()
clf=lin_clf.fit(X_train, y_train)
y_pred_class = clf.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(datetime.now() - t1)

In [ ]:
#CountVectorizer
vect = CountVectorizer()
train_dtm = vect.fit_transform(X_train)
test_dtm = vect.transform(X_test)

train_dtm

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res , test_size=0.3, random_state=100)

#RandomUnderSampler
from imblearn.under_sampling import RandomUnderSampler

t1 = datetime.now()
print('Original dataset shape {}'.format(Counter(y)))
rus = RandomUnderSampler(random_state=100)
X_res, y_res = rus.fit_sample(train_dtm, y)
print('Resampled dataset shape {}'.format(Counter(y_res)))
print(datetime.now() - t1)

In [ ]:
from collections import Counter

def balance_classes(xs, ys):
    freqs = Counter(ys)

# the least common class is the maximum number we want for all classes
    max_allowable = freqs.most_common()[-1][1]
    num_added = {clss: 0 for clss in freqs.keys()}
    new_ys = []
    new_xs = []
    for i, y in enumerate(ys):
        if num_added[y] < max_allowable:
            new_ys.append(y)
            new_xs.append(xs[i])
            num_added[y] += 1
    return new_xs, new_ys

In [ ]:
# split the new DataFrame into training and testing sets

In [ ]:
print(Counter(y))
balanced_x, balanced_y = balance_classes(X, y)
print(Counter(balanced_y))

In [ ]:
balanced_x

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(balanced_x, balanced_y, test_size=0.3, random_state=100)

In [ ]:
vect = CountVectorizer()
train_dtm = vect.fit_transform(X_train)

test_dtm = vect.transform(X_test)


In [ ]:
X_test

In [ ]:
test_dtm

In [ ]:
train_dtm

In [ ]:
from sklearn.svm import LinearSVC
#LinearSVC
lin_clf = LinearSVC()
lin_clf.fit(train_dtm, y_train)
y_pred_class = logreg.predict(test_dtm)
print(classification_report(y_test,y_pred_class))

In [ ]:
#LogisticRegression
logreg = LogisticRegression(C=1e9)
logreg.fit(train_dtm, y_train)
y_pred_class = logreg.predict(test_dtm)
print (metrics.accuracy_score(y_test, y_pred_class))

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred_class ))
print('\n')
print(classification_report(y_test, y_pred_class))

In [ ]:
texts=data['review_body'].values
stars=data['star_rating']

In [ ]:
#balance_class

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from datetime import datetime

In [ ]:
# This vectorizer breaks text into single words and bi-grams
# and then calculates the TF-IDF representation
vectorizer = TfidfVectorizer(ngram_range=(1,2))
t1 = datetime.now()

# the 'fit' builds up the vocabulary from all the reviews
# while the 'transform' step turns each indivdual text into
# a matrix of numbers.
vectors = vectorizer.fit_transform(balanced_x)
print(datetime.now() - t1)

In [ ]:
print(X_train)

In [ ]:

from sklearn.svm import LinearSVC
# initialise the SVM classifier
classifier = LinearSVC()
 
# train the classifier
t1 = datetime.now()
classifier.fit(X_train, y_train)
print(datetime.now() - t1)

In [ ]:
preds = classifier.predict(X_test)
print(list(preds[:10]))
print(y_test[:10])


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, preds))
 
